server:
  port: 18080

spring:
  application:
    name: user-service

dubbo:
  reference:
    check: false
  consumer:
    check: false
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://127.0.0.1:2181
    check: false
  metadata-report:
    # dubbo-admin需要这个配置上报meta信息
    address: zookeeper://127.0.0.1:2181
  application:
    name: ${spring.application.name}