server:
  port: 18080

spring:
  application:
    name: user-service

dubbo:
  protocol:
    name: dubbo
    port: 7788
  registry:
    address: zookeeper://127.0.0.1:2181
    username: user-name
  metadata-report:
    # dubbo-admin需要这个配置上报meta信息
    address: zookeeper://127.0.0.1:2181