server:
  port: 18090

spring:
  application:
    name: consumer-service

dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://127.0.0.1:2181
  metadata-report:
    # dubbo-admin需要这个配置上报meta信息
    address: zookeeper://127.0.0.1:2181
  application:
    name: ${spring.application.name}