server:
  port: 8200

spring:
  application:
    name: order-service

dubbo:
  # 全局超时
  consumer:
    check: false
  # 统一设置服务提供方的规则
  provider:
    timeout: 2000
    retries: 5
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://127.0.0.1:2181
    check: false
  metadata-report:
    # dubbo-admin需要这个配置上报meta信息
    address: zookeeper://127.0.0.1:2181
  application:
    name: ${spring.application.name}